### ISSUE TITLE
avast Alert

### ISSUE THREAD

**Issue by tulving** [jonaskohl/CapsLockIndicator#4]
Hi, 

Avast antivirus blocks CapsLockIndicator, reporting IDP.ALEXA.51 presence on .exe file.

Thanks

**Comment by jonaskohl** [comment]
This is caused by it checking for updated via the internet and also its ability to launch on startup. It's a false positive. I have contacted Avast about this (see #3 ). I also made a test with [VirusTotal](https://www.virustotal.com/#/url/a861b71d99c06301dd39042f2938a827151beede2329f892b0fc068429619b81/detection) with 0/66 detections.
