### ISSUE TITLE
Custom icons disabled if "Start on logon" is selected

### ISSUE THREAD

**Issue by EverEve** [jonaskohl/CapsLockIndicator#47]
Hello, I've noticed that the custom icons are not shown if the option "Start on logon" is selected. If it is manually started after the logon, my custom icons are shown normally.

Is it possible to solve? I ask this since the boxed capital C is not very easy to detect and I wish to use black letters in white background. 

Thanks.

**Comment by jonaskohl** [comment]
Hmm, normally there should be no difference. My best guess at what is happening is that the working directory is different when automatically starting, so it no longer sees the icon files in the current directory. (Reference: [MainForm.cs#L124](https://github.com/jonaskohl/CapsLockIndicator/blob/master/CapsLockIndicatorV3/MainForm.cs#L124)

**Comment by EverEve** [comment]
Hello, I can confirm the behavior: the program is executed from D:\Prog\CapsLock and in that directory are also the icon files. 
If I run the program normally, the icons are the ones I put in that directory. If I make it running at logon, the icons are the default ones.
If you want, I can upload the icon files.

**Comment by jonaskohl** [comment]
Okay, I think I found the problem. When an application is auto-run using a registry entry in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`, it is always run in `%systemroot%\SysWOW64` instead of the directory the executable is in.

![sc_comp_00](https://user-images.githubusercontent.com/23175424/78795106-df8f3500-79b4-11ea-817b-d851b8da525e.png)

A temporary fix would be to uncheck "Start on logon" and instead copying a shortcut to CLI into the autorun folder by typing `shell:startup` into the run box.

**Comment by EverEve** [comment]
I've tried in past days and it used to work.

Anyway, if you are going to solve the problem, I will be thankful.

**Comment by jonaskohl** [comment]
This should finally be fixed. If not, let me know and I'll reopen the issue.
