### ISSUE TITLE
Windows defender blocks the install

### ISSUE THREAD

**Issue by fxpar** [jonaskohl/CapsLockIndicator#52]
Sorry for the french
![image](https://user-images.githubusercontent.com/11584406/89657861-0e1f0d00-d8ce-11ea-98a4-3299cfda14e0.png)

**Comment by jonaskohl** [comment]
That is because Windows Defender basically blocks all apps that it doesn't know from running. There is unfortunately nothing I can do to fix this. But be assured, all binaries of CapsLock Indicator are 100% safe! If you still don't trust them, there's always the possibility for you to download the source code and compile the binary yourself.

**Comment by fxpar** [comment]
Oh! it is a pity that microsoft doesn't provide a code or a certificate to avoid this. Hopefully your application will soon be recognized by SmartScreen.

**Comment by fxpar** [comment]
The EV Code from digicert is 664$ /year 😱... As your tool is very very useful on Acer laptops which lack the leds, they should offer you this certificate! 😀

**Comment by jonaskohl** [comment]
I definitely cannot afford a certificate for $664 a year. Funnily enough, the laptop I started this project for was actually an Acer model 😅
